name: see

on: 
  # workflow_dispatch:
  push:
    branches:
      - main
    
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR

jobs:
  build-machine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::882743124337:role/infra-sls-role
          # role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-south-1
          role-session-name: GitHub-OIDC-TERRAFORM
    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        env:
          AWS_BUCKET_NAME: github-oidc-aws-tfstates-lk
          AWS_BUCKET_KEY_NAME: infra2.tfstate
          AWS_REGION: ap-south-1
        run: |
          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
          terraform validate -no-color

      - name: Plan and Apply
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan  

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        # - run: npm ci

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
      # - run: npm install -g serverless
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}